version: '3.1'

services:
  db:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pexample" ]
      interval: 10s
      retries: 3
      timeout: 10s
    networks:
      - task-tracker

  frontend:
    build:
      context: frontend
      dockerfile: ../frontend/Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - task-tracker


volumes:
  minio_storage: {}

networks:
  task-tracker:
    driver: bridge
