server:
  port: 8765

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: backend-service
          uri: lb://backend
          predicates:
            - Path=/user

        - id: backend-service-tasks
          uri: lb://backend
          predicates:
            - Path=/tasks

        - id: backend-service-auth
          uri: lb://backend
          predicates:
            - Path=/auth/login

      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            exposed-headers:
              - Authorization
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PATCH
              - PUT
              - DELETE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
